
remote_theme: pmarsceill/just-the-docs

lang: en

title: Just the Docs

description: A Jekyll theme for documentation

baseurl: "/just-the-docs/" # the subpath of your site, e.g. /blog

permalink: pretty

exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

search_enabled: true # Enable or disable the site search

color_scheme: nil # Color scheme currently only supports "dark" or nil (default)

ga_tracking: # Google Analytics Tracking (optional)

aux_links: # Aux links for the upper right navigation
  "Just the Docs on GitHub":
    - "//github.com/pmarsceill/just-the-docs"

